---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: route53-credentials
  namespace: cert-manager
spec:
  # IAM user: on-prem-letsencrypt
  # Check out infra/aws/k8s-iam/letsencrypt.tf (from codedang repo)
  encryptedData:
    aws_access_key_id: AgBrdP0K6cV7M9EyXahAPXwshm8ZaxD3OeCWCnd7e1fIhACe3fDQStSlgD9YmqYLTYASmeZu8j+G9XDMgodRsPQhf0VuiE3E34SeGJJ9HmB6kggJ69gsHtGrCwyKyoowQfV5vgIedlJvxgDFLCggeOvY+VHY52ZdMOaC4r4oOTRLGJwE++VCCehBn6TMwqYbgD2WzVzc63Z6W9n4l3oScBdoWDeysRTF4dDryB+d8SsW8YvVcjAg0ywPaJJjUtWlMpMZwda4lEEr5qrSRECxpEp8rdDeu91iPtLebvliNfRZK7UwEmM/mNU2jPXqg8aLJyg4YosySQOcxGEICOSdciGMDKVkae48tvIQmga56IM4u6pPkFIrS/AUp53uTjFfCedC6bWK5qfVyPpsOLK7aA83OMrdLmAXVvUjhAwhNeHWldqTi/UChRCkGzil36rRkJhpzb1z9/Qfx9TBTtffzv0RHEczisPWmH4xgiF+A7Jzhk8XcNohnH/B1q9POAeAIybZIAiHcm6AX+clqI+UMg5Uawbdma+Tb/zv+pwC2PgUia9vsyRXM81Pi+RrsJdNQULoylagQnQizSxQgpIO0Vo7UTCdsIeBYDJ1Plh29BbHwl/X8lgNugO6wStRzj7RXijFMpT7SvD+xobbXh3S1rfQ6kw6urA4YQ5S2DfVToV9ZPMshxJGKAFZSZzraSEXUxeFeQFj0UElof8mYzpmfaC+l2Nn1g==
    aws_secret_access_key: AgAG5fBfQMMa2WsGVOq1xVlzxkDwUd5cFiyMu4gSbkClRV4Gwiyf3A7GDm2q+HBvK6ccfQKM2hzg9fsUXg4o6d1Vl4fP8r4WJMioOFcgUu57mSyB9JCwxGPlmPpQAp55qsEYhWF/IPh0vByYMYLUev+ee5k4sRZpUm1PKdpzv0x5HT4r7RcgqFOlCrwjoruuN7xcKlrTxOmlx3VJVdiOV/G1oe32W2oO+LeMXhwWXypiwkSdQUX+FPMuHm39Lgc/sOJBQ80KsCIKtyKcbRLIeyHXjChikqbF6JIVeP4kJHLe6fHPIh3I9cVlRhCYVCP3qGtU9GyqYp3vb422fRLJ6d2UeF9vqNpz8nAY7i8JIWze7bbUc5eRacwkWztNTYmUb6OMfEW1rjNjd5sOAM0rk0xgfpNO/Q7JzbR+Id/LQ8jsS3zr9OJUp8WIP4RWlEJAq3VVFDJ23hrB42wjLLXGjxilKPXGGxIZ5Yy/SVjpjj3Rs6L47Ex3eanS40SLyQnsu2GDGH+XazdLiJgMWuVa61rusAX6IjuGDt8aaRquySHV5zochjOAvW9cSkgLJSJLoTzTPCdpf7C6aR+69pASX8MffdIoBKjdaS2z0SvBxJyU77qLAaJuLWKpreTUfEVbHbV2ZJzf6KQfHRw297zsuHsV5b0MXWnzoFbsIvYcA+hwDHOpZ8CQObOxZPaAwr7zhKhGQTM/S3vF93D6SABfcjxUZCRum7xW3W0+WRiZwRa31BsbpuCxSMEB
  template:
    metadata:
      name: route53-credentials
      namespace: cert-manager
    type: Opaque